# Generated by Django 4.0.1 on 2022-01-30 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(default='', max_length=32)),
                ('seller_name', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_password', models.CharField(default='', max_length=32)),
                ('user_phone', models.CharField(default='', max_length=32)),
                ('booking_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_id', models.CharField(default='', max_length=32)),
                ('product_img', models.ImageField(default='', upload_to='images')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.seller_tb')),
            ],
        ),
        migrations.CreateModel(
            name='book_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField(default='', max_length=100)),
                ('book_to', models.DateField(default='', max_length=100)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.seller_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.user_tb')),
            ],
        ),
    ]
