# Generated by Django 4.0.1 on 2022-02-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameraRentApp', '0002_rename_product_id_product_tb_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.DateField(default='', max_length=100)),
                ('book_to', models.DateField(default='', max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.product_tb')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.seller_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.user_tb')),
            ],
        ),
    ]
