# Generated by Django 4.0.1 on 2022-02-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameraRentApp', '0003_book_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_tb',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='book_tb',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='book_tb',
            name='user_id',
        ),
    ]
