# Generated by Django 4.0.1 on 2022-02-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameraRentApp', '0004_remove_book_tb_product_id_remove_book_tb_seller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tb',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.product_tb'),
        ),
        migrations.AddField(
            model_name='book_tb',
            name='seller_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.seller_tb'),
        ),
        migrations.AddField(
            model_name='book_tb',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cameraRentApp.user_tb'),
        ),
    ]
