# Generated by Django 4.0.1 on 2022-02-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraRentApp', '0005_book_tb_product_id_book_tb_seller_id_book_tb_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tb',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='product_tb',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
    ]
