# Generated by Django 4.0.1 on 2022-02-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameraRentApp', '0006_book_tb_status_product_tb_status_seller_tb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='status',
        ),
    ]
