# Generated by Django 4.0.1 on 2022-02-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameraRentApp', '0007_remove_product_tb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_tb',
            name='status',
        ),
    ]
